SELECT REQ_CODE, RC.CA_NAME, M.M_NAME, R.REQ_SUBJECT,R.REQ_CONTENT , TO_CHAR(R.REQ_DATE, 'yyyy-mm-dd'), R.REQ_REPORT, RR.RES_NAME 
FROM REQUEST R 
INNER JOIN REQ_CATEGORY RC 
ON RC.CA_CODE = R.REQ_CACODE 
INNER JOIN MEMBER M 
ON M.M_CODE = R.REQ_MCODE 
INNER JOIN REQ_RESULT RR 
ON RR.RES_CODE = R.REQ_RESCODE 
where R.REQ_RESCODE ='404' and R.REQ_CACODE ='201'
ORDER BY R.REQ_CODE DESC



SELECT M_CODE, M_NAME FROM MEMBER;


SELECT M_CODE, M_NAME, D.DEP1_NAME, M_EXTENSION, M_PHONE, M_MOBILE, M_MAIL, P.POS_NAME, M_ID, M_PWD FROM MEMBER M INNER JOIN DEPARTMENT1 D ON M.M_DEPCODE= D.DEP1_CODE INNER JOIN POSITION P ON M.M_POSCODE = P.POS_CODE WHERE D.DEP1_CODE = '135'
ORDER BY M_NAME ASC

SELECT M_CODE, M_NAME, D.DEP1_NAME, M_EXTENSION, M_PHONE, M_MOBILE, M_MAIL, P.POS_NAME, M_ID, M_PWD 
FROM MEMBER M 
INNER JOIN DEPARTMENT1 D 
ON M.M_DEPCODE= D.DEP1_CODE 
INNER JOIN POSITION P 
ON M.M_POSCODE = P.POS_CODE
WHERE D.DEP1_CODE = '301' OR P.POS_CODE = 301
ORDER BY M_NAME ASC;


select * from DEPARTMENT1;

SELECT M_CODE, M_NAME,P.POS_CODE, D.DEP1_NAME, M_EXTENSION, M_PHONE, M_MOBILE, M_MAIL, M_MAIL, P.POS_NAME, M_ID, M_PWD

FROM MEMBER M 
INNER JOIN DEPARTMENT1 D
ON M.M_DEPCODE= D.DEP1_CODE
INNER JOIN POSITION P 
ON M.M_POSCODE = P.POS_CODE

select pos_code, pos_name from POSITION; 

select dep1_code, dep1_name from DEPARTMENT1 order by dep1_name asc;

SELECT M_CODE, M_NAME, M_DEPCODE, M_EXTENSION, M_PHONE, M_MOBILE, M_MAIL,M_POSCODE, M_MAIL, M_ID, M_PWD

FROM MEMBER ;

DELETE FROM MEMBER WHERE M_CODE =''


UPDATE Member SET m_name='이현경', m_depcode='133', m_extension='892', m_phone='010-6767-8804', m_mobile='010-6767-8804',m_mail='lhkgogo7@nate.com',m_poscode='302',m_id='',m_pwd=''where m_code='M0002';
select * from member;

select * from position;

INSERT into MEMBER(M_CODE, M_NAME, M_DEPCODE, M_EXTENSION, M_PHONE, M_MOBILE, M_MAIL,M_POSCODE, M_ID, M_PWD) 
values('M'||LPAD(MCODE_SEQ.NEXTVAL,4,0),'정경민','102','428','070-4877-6182','010-9073-7912','','310','','');


SELECT "M"||LPAD(MCODE_SEQ.NEXTVAL,4,0) FROM DUAL;


SELECT EQ_CODE, EQ_NAME, EQ_MANUFACTURER, EC.EQ_CA_NAME,EQ_EQCACODE, TO_CHAR(EQ_DATE, 'yyyy-mm-dd')  FROM EQUIPMENT EQ INNER JOIN EQ_CATEGORY EC ON EC.EQ_CA_CODE = EQ.EQ_EQCACODE
where eq_ca_code= 508














